apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muvico-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: muvico=quay.io/muvico_hy/muvico
    argocd-image-updater.argoproj.io/muvico.update-strategy: newest-build
    argocd-image-updater.argoproj.io/muvico.allow-tags: regexp:^sha-[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/muvico.kustomize.image-name: quay.io/muvico_hy/muvico
spec:
  project: muvico-staging
  source:
    repoURL: https://github.com/MuViCo/gitops.git
    targetRevision: main
    path: environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
