apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muvico-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: muvico
  source:
    repoURL: https://github.com/MuViCo/gitops.git
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
